version: "3"

services:

    server:
        build:
            context: ./
            dockerfile: ./Dockerfile
        env_file:
            - ./.env
        command: nodemon app.js
        volumes:
            - .:/app
        ports:
            - 3000:3000